name: dotnet build
on:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - component: server
            project: Server
            test-project: ServerTest
          - component: masterserver
            project: MasterServer
            test-project: LmpMasterServerTest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Install dependencies
        run: dotnet restore ${{ matrix.project }}
      - name: Build
        run: dotnet build ${{ matrix.project }}
      - name: Test
        run: dotnet test ${{ matrix.test-project }}
