name: Docker build
on:
  pull_request:

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_push:
    name: Build Docker image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: server
            dockerfile: Dockerfile_Server
          - image: masterserver
            dockerfile: Dockerfile_MasterServer
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          config: .github/buildkitd.toml
      - name: Build container image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
